function(skyrocket_add_test name)
    set(srcs)
    foreach(s IN LISTS ARGN)
        if (NOT IS_ABSOLUTE "${s}")
            get_filename_component(s "${s}" ABSOLUTE)
        endif ()
        list(APPEND srcs "${s}")
    endforeach()
    list(APPEND srcs "${CMAKE_CURRENT_SOURCE_DIR}/TestMain.cpp")
    add_executable(${name} "${srcs}")
    target_include_directories(${name} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
    target_link_libraries(${name} Skyrocket)
endfunction()